---
terrains:
  - id: sea_alt
    name: terrain_name_sea
    biomeNames:
      volcano: terrain_name_sea_lava
    biomeDescriptions:
      volcano: terrain_description_lava
    defenceBonus: 1
    movementCost:
      sailing: 1
      flying: 1
      hovering: 1
      amphibious: 1
      sea_building: 1
    biomeMovementCosts:
      volcano:
        flying: 1
        hovering: 1
    movementGroupType: water
    placeable: true
    tilesets:
      0: [plains, rough]
      1: sea_alt

  - id: rough
    name: terrain_name_rough
    defenceBonus: 2
    movementCost:
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      wheels: 3
      amphibious: 2
      land_building: 1
      indoor_building: 1
    movementGroupType: land
    placeable: true
    tilesets:
      0: rough
      
  - id: cave_wall
    name: terrain_name_wall
    defenceBonus: 0
    movementCost:
      flying: 0
    movementGroupType: land
    visionBlocking: true
    placeable: true
    tilesets:
      0: [plains, rough]
      2: cave_wall
      
  - id: slope
    name: terrain_name_wall
    defenceBonus: 4
    movementCost:
      walking: 3
      flying: 1
      hovering: 1
      sea_building: 1
      land_building: 1
      indoor_building: 1
    movementGroupType: land
    placeable: true
    tilesets:
      0: [plains, rough]
      1: slope
      
  - id: deck
    name: terrain_name_deck
    defenceBonus: 1
    movementCost:
      walking: 1
      riding: 1
      flying: 1
      hovering: 1
      wheels: 1
      amphibious: 2
      land_building: 1
      indoor_building: 1
    movementGroupType: land
    placeable: true
    tilesets:
      1: ocean
      2: deck
      
  - id: invisible_wall_ocean
    name: terrain_name_hull
    defenceBonus: 0
    movementCost:
      flying: 1
    movementGroupType: land
    visionBlocking: true
    placeable: true
    tilesets:
      0: [plains, rough]
      1: invisible_wall_ocean

  - id: invisible_wall_sea
    name: terrain_name_hull
    defenceBonus: 0
    movementCost: 
      flying: 1
    movementGroupType: land
    visionBlocking: true
    placeable: true
    tilesets:
      0: [plains, rough]
      1: invisible_wall_sea
      
  - id: invisible_blocker_ocean
    name: terrain_name_cabin
    defenceBonus: 0
    movementCost: {}
    movementGroupType: land
    visionBlocking: true
    placeable: true
    tilesets:
      0: [plains, rough]
      1: invisible_blocker_ocean
...